{{- if .Values.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zipkin.collector.serviceAccountName" . }}
  labels:
    {{- include "zipkin.collector.labels" . | nindent 4 }}
  {{- with .Values.collector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
