apiVersion: v1
kind: Service
metadata:
  name: {{ include "zipkin.collector.fullname" . }}
  labels:
    {{- include "zipkin.collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zipkin.collector.selectorLabels" . | nindent 4 }}
