apiVersion: v1
kind: Service
metadata:
  name: {{ include "zipkin.collector.fullname" . }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.port }}
      targetPort: {{ .Values.collector.service.targetPort }}
      protocol: {{ .Values.collector.service.protocol }}
      name: {{ .Values.collector.service.name }}
  selector:
    {{- include "zipkin.selectorLabels" . | nindent 4 }}
