apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zipkin.collector.fullname" . }}
  labels:
    {{- include "zipkin.collector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.collector.autoscaling.enabled }}
  replicas: {{ .Values.collector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zipkin.collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zipkin.collector.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zipkin.collector.serviceAccountName" . }}
      containers:
        - name: {{ include "zipkin.collector.fullname" . }}
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          env:
            - name: QUERY_PORT
              value: {{ .Values.collector.service.targetPort | quote }}
            {{- range .Values.collector.env }}
            - {{ . | toYaml }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.collector.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
      {{- with .Values.collector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.collector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.collector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
