{{- if .Values.dependencies.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zipkin.dependencies.serviceAccountName" . }}
  labels:
    {{- include "zipkin.dependencies.labels" . | nindent 4 }}
  {{- with .Values.dependencies.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
